apps:
    web:
        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:388kJL7yzy9NkFMgfs3/pP3XIviyJXOs/HGbE2FEJZg/MIfAWg0XaZBxV/fET+m4OO6us5t9N2mTVv9EW4Qhkg==,iv:PkwIfCdzxm1+31eDExaC/ctnq9B2b3lKYSLZzJluZ3E=,tag:XIHMmnSAuryCms1CWqi/Ag==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:BBFu7qaJzxeWwLj+seEX6w9ASpi2oIjectUKW/SR1HWAOj8ztZMlA3Z9S8P5dKg=,iv:vCWi9cD66sENKh2ssu+ph9IZrOfHQLA6w5ijV1p7cno=,tag:i+Z1+2bNyLd33SY8M+RPLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbkFtUllkaVBFSk9CQWlU
            ekNzMTBKZ1Fjd0dnNmpKZEFjUmVpYmNTUzNZCi81blVpc3ZzTFFhNURRTW5tN3Zu
            T3Z3SVVCLzA1K2FucU1hYlp4OUhrZnMKLS0tIEVXaGtpcGdZd1hXK213Z2V0ekI2
            VFBIdy9CdWIzTUJmbERwRDNNd0VSYncKPDB3TvYJo8Gi3I7iqJ3mHkV4BjxZMn87
            402Ec9ZWF/5x4fAOq8srLnA6ifJfYwmwWbFsbqyDHUMIz+3T6moZHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybmhlSk9tS2IwcDQxd0xh
            d01GOTNwcFBleWh4elZidGR3Skg3N2xQbldVCmtZNklZdFRRcTREcERhdzBVZUxo
            eCt5bnBVM3V4VWxwcFhiQTd5eGRsR28KLS0tIHNhT3VEUHRlTWNrNmhlNWJFVG1N
            dDlHRDBTdnZ4NVdOZy8zMkl6TWpDWGMKxkNTYMZMNTvuDD9+/UmXYHsJOzji5Sf+
            uB0Jjr8gBrY3X/xZD/Fwt26eiTW+9/DiA6TUZluiOO3u/Yj6ABRuYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cgudsv52h62snquglvayft2n4ck522x4at5aja57un06w9w0gszqzfqtce
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXUvZTBjS3hiRCt5SkpP
            ZElyS2xPdDQrZjRsK1dJd25JS2ozWEFXMEhNCjB5cHVvcVNPelZWRlZGRXpCd2po
            MnB0SVhzQVd5R0ZSRE9GckJXalN0bDAKLS0tIFo3R2FBczk0d0lZb093dkpyU3B5
            TEdacldxdFloVm9sclFXbFFvYU9HdnMKkYTMa884H+sH8NrvA3thB8jgK1+wLCM2
            BNvKp96Eu6hzLTTd49DhanP5+H3ZPXCiP1bHM/Bm143nONSsRXKkSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j4lkxpdweugkfz900u023kx8p6k7yuhdp8jmxthj0qse3w6ahfesyqnj96
    lastmodified: "2026-08-23T12:41:49Z"
    mac: ENC[AES256_GCM,data:zj6ay3HNC5PozmrohGQRmMrgZWpEJGuwTjpMD2bGxJ9D82eayW39UKy/d5UsZcC71nQoJU83sJIGvQwN7OGSw85L2pngdLYBobP0oCqp0ZbpH1OqJs4RLckd4LuQriqZ7Ytm2R8FPrhJGHiEJIqjTm9fjP+xcBZoBOhLHo6pUas=,iv:7lekKcndsLqvOJsDA87jUqAaJzln80EQE1bjwAuhI3I=,tag:V2X4FSW8V5be8elRTO6Gog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
